---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=password123
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=suitecrm
      - MARIADB_USER=suitecrm
    ports:
      - "3306:3306"
    networks:
      - suitecrm

  suitecrm-server:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb
    networks:
      - suitecrm
    restart: on-failure # Added this to give maria_db to configure for testing purposes
    healthcheck:
      test: ["CMD", "ansible-playbook", "oldupstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  suitecrm: