---
- name: Suite-Crm
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Include nodeType variables
      include_vars:
        file: "vars/{{ BUILD_ENVIRONMENT }}.yml"
      tags:
        - always
      ignore_errors: yes
    - name: Include Special Variables
      include_vars:
        file: "vars/{{ lookup('env', 'COMPUTE_ENV') | default( 'base', True) }}.yml"
      ignore_errors: yes
# Need to put this in here to start the database before running commands to install databse in app
    - name: Run tests to make sure app is running as expected
      include_tasks:
        file: jobs/tests/test.yml
    - name: Run And Configure
      include_tasks:
        file: jobs/run/run.yml
    - name: Execute application
      include_tasks:
        file: jobs/run/exec.yml

