---
- name: Install Restyaboard server
  hosts: localhost
  connection: local
  vars_files:
    - vars/prod.yml
  tasks:
    - name: Install Suite CRM Dependencies
      include_tasks:
        file: jobs/build/install_dependencies.yml
        apply:
          tags:
          - nginx
          - php
          - build
      tags:
      - nginx
      - php
      - build

    - name: Install SuiteCRM
      include_tasks:
        file: jobs/build/install_suitecrm.yml
        apply:
          tags:
          - suitecrm
          - build
      tags:
        - suitecrm
        - build

    - name: Generate SSL certificate
      include_tasks:
        file: jobs/run/ssl_generate.yml
        apply:
          tags:
          - sslcertificate
          - run
      tags:
      - sslcertificate
      - run

    - name: Configure NGINX
      include_tasks:
        file: jobs/run/config_nginx.yml
        apply:
          tags:
          - nginx
          - run
      tags:
      - nginx
      - run

    - name: Run nginx
      include_tasks:
        file: jobs/run/nginx.yml
        apply:
          tags:
            - nginx
            - run
      tags:
        - nginx
        - run

#    - name: Configure restyaboard
#      include_tasks:
#        file: jobs/run/restyaboard_config.yml
#        apply:
#          tags:
#          - config-restyaboard
#          - run
#      tags:
#      - config_restyaboard
#      - run

    - name: Test database connectivity
      include_tasks:
        file: jobs/tests/database_test.yml
        apply:
          tags:
          - database
          - test
          - run
      tags:
      - database
      - test
      - run

    - name: Test Nginx
      include_tasks:
        file: jobs/tests/nginx_test.yml
        apply:
          tags:
          - nginx
          - test
          - run
      tags:
      - nginx
      - test
      - run

    - name: Test URL
      include_tasks:
        file: jobs/tests/url_test.yml
        apply:
          tags:
            - url
            - test
            - run
      tags:
        - url
        - test
        - run

    - name: Execute NGINX
      include_tasks:
        file: jobs/exec/nginx.yml
        apply:
          tags:
          - exec
      tags:
      - exec
