---
- name: Template nginx config file to /etc/nginx/nginx.conf
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Template fastcgi_params file to etc/nginx/nginx.conf
  template:
    src: templates/fastcgi_params.j2
    dest: /etc/nginx/fastcgi_params

- name: Remove default file /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Template a file to etc/nginx/sites-enabled
  template:
    src: templates/suitecrm_site.j2
    dest: /etc/nginx/sites-enabled/"{{ organization.hostname }}"